ImmoInfoWebApp/Controllers/ProprieteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImmoInfoWebApp.Service;
using ImmoInfoWebApp.Models;
namespace ImmoInfoWebApp.Controllers
{


    public class ProprieteController : Controller
    {


        WebAppService appService = new WebAppService();
        // GET: Propriete
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles ="ADMIN")]
        public ActionResult ListPropriete()
        {

            List<ProprieteModel> proprieteModels = appService.findAllPropriete();
            ViewBag.listePropriete = proprieteModels;
            return View();
        }

        public ActionResult ListProprieteClient()
        {
            List<ProprieteModel> proprieteModels = appService.findAllProprieteParClient(User.Identity.Name);
            ViewBag.listePropriete = proprieteModels;
            return View("ListPropriete");
        }

        public ActionResult DetailProprite() {

            return View();

        }
    }
}

ImmoInfoWebApp/Views/Propriete/ListPropriete.cshtml
@using ImmoInfoWebApp.Models
@{
    ViewBag.Title = "ListPropriete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section styles {
    @Styles.Render("~/datatablestb/css")
}
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">

    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">

            <!--begin::Card-->
            <div class="card card-custom">
                <div class="card-header flex-wrap py-5">
                    <div class="card-title">
                        <h3 class="card-label">
                            Liste Proprieté
                            <div class="text-muted pt-2 font-size-sm">Affichage de la liste des propriété</div>
                        </h3>
                    </div>
                    <div class="card-toolbar">

                         <!--begin::Button-->
                        <a href="#" class="btn btn-primary font-weight-bolder">
                            <span class="svg-icon svg-icon-md">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <circle fill="#000000" cx="9" cy="15" r="6" />
                                        <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span>Nouvelle Proprieté
                        </a>
                        <!--end::Button-->

                    </div>
                </div>
                <div class="card-body">
                    <!--begin: Datatable-->
                    <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                        <thead>
                            <tr>
                                <th>Ville / Adresse</th>
                                <th>Montant</th>
                                <th>Monnaie</th>
                                <th>Perimetre </th>
                                <th>Superficie</th>
                                <th>Proprietaire</th>
                                <th>Statut</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (ProprieteModel pp in ViewBag.listePropriete)
                            {
                                <tr>
                                    <td>@(pp.VilleLibelle +" "+pp.Adresse )</td>
                                    <td>@pp.MontantSouhaite</td>
                                    <td>@pp.MonnaieLibelle</td>
                                    <td>@pp.Perimetre</td>
                                    <td>@pp.Superficie</td>
                                    <td>@pp.RefPropNom</td>

                                    <td>

                                        @if (pp.Statut == 1)
                                        {
                                            <span class='label-dot mr-2 label label-success'></span>
                                            <span class="font-weight-bold text-success"> @pp.StatutLibelle</span>
                                        }
                                        else
                                        {

                                            if (pp.Statut == 2)
                                            {
                                                <span class='label-dot mr-2 label label-danger'> </span>
                                                <span class="font-weight-bold text-danger"> @pp.StatutLibelle</span>
                                            }
                                            else
                                            {
                                                <span class='label label-warning label-dot mr-2 '> </span>
                                                <span class="font-weight-bold text-warning"> @pp.StatutLibelle</span>
                                            }

                                        }


                                    </td>

                                    <td nowrap="nowrap">

                                        <div class="dropdown dropdown-inline">

                                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon" data-toggle="dropdown">

                                                <i class="la la-cog"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">

                                                <ul class="nav nav-hoverable flex-column">
                                                    <li class="nav-item"><a class="nav-link" href="#" onclick="@($"OpenModalPopUp({pp.IdProp}); return false");"><i class="nav-icon la la-edit"></i><span class="nav-text">Enchere</span></a></li>
                                                    <li class="nav-item"><a class="nav-link" href="@Url.Action("DetailProprite", "Propriete")"><i class="nav-icon la la-leaf"></i><span class="nav-text">Détails</span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <a href="javascript:;" class="btn btn-sm btn-clean btn-icon" title="Edit details">

                                            <i class="la la-edit"></i>
                                        </a>
                                        <a href="javascript:;" class="btn btn-sm btn-clean btn-icon" title="Delete">

                                            <i class="la la-trash"></i>
                                        </a>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                    <!--end: Datatable-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
</div>
<!--end::Content-->

<!-- Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Changement Statut Compte</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            @using (Html.BeginForm("ChangementStatut", "Proprietaire", FormMethod.Post, new { @class = "form" }))
            {
                <div class="modal-body">

                    @Html.Hidden("IdUtil", new { id = "IdUtil" })

                    @*@Html.DropDownList("IdStatut", new SelectList(
                                                               ViewBag.statutCmpt, "IdStatutCpte", "Description"
                                                          ), new { id = "IdStatut", @class = "form-control" })*@

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary font-weight-bold">Valider</button>
                </div>

            }
        </div>
    </div>
</div>


@section Scripts
{
    @Scripts.Render("~/bundles/datatablestb")
    @Scripts.Render("~/bundles/columnrendering")

    <script type="text/javascript">

        //alert("GOD my life")
        function OpenModalPopUp(reservationDay) {
            //alert(reservationDay);
            $('#IdUtil').val(reservationDay);
            $('#exampleModal').modal();
        };
    </script>

}